
apiVersion: apps/v1
kind: Deployment
metadata:
spec:
  template:
    spec:
      containers:
      - name: timber-frontend
        env:
        - {name: TIMBER_BACKEND_API_URL, value: "http://timber-backend:8080"}
